Avoiding very mysterious error in pyreport.
Isolated to the line were the random permutation is done, but I'm utterly clueless about the cause.

Traceback (most recent call last):
  File "/usr/local/bin/pyreport", line 9, in <module>
    load_entry_point('pyreport==0.3.4c', 'console_scripts', 'pyreport')()
  File "/usr/local/lib/python2.7/dist-packages/pyreport-0.3.4c-py2.7.egg/pyreport/pyreport.py", line 57, in commandline_call
    main(pyfile, overrides=options)
  File "/usr/local/lib/python2.7/dist-packages/pyreport-0.3.4c-py2.7.egg/pyreport/main.py", line 1120, in main
    output_list = execute_block_list(block_list, options)
  File "/usr/local/lib/python2.7/dist-packages/pyreport-0.3.4c-py2.7.egg/pyreport/main.py", line 318, in execute_block_list
    output_list = map(execute_block, block_list)
  File "/usr/local/lib/python2.7/dist-packages/pyreport-0.3.4c-py2.7.egg/pyreport/code_hasher.py", line 160, in itercodeblocks
    for codeline in self.itercodelines():
  File "/usr/local/lib/python2.7/dist-packages/pyreport-0.3.4c-py2.7.egg/pyreport/code_hasher.py", line 193, in itercodelines
    for token in self.itertokens():
  File "/usr/local/lib/python2.7/dist-packages/pyreport-0.3.4c-py2.7.egg/pyreport/code_hasher.py", line 209, in itertokens
    for token_desc in tokenize.generate_tokens(self.next_line_generator):
  File "/usr/lib/python2.7/tokenize.py", line 361, in generate_tokens
    pseudomatch = pseudoprog.match(line, pos)
TypeError: array cannot be safely cast to required type